### ISSUE TITLE
Request for help -- running swagger cli from docker container

### ISSUE THREAD

**Issue by rpgoldman** [magoyette/flycheck-swagger-cli#1]
I was going to run the swagger CLI from a docker container, using this command:

    docker run --rm jeanberu/swagger-cli swagger-cli

But when I try, `flycheck-swagger-cli` is disabled, and in the information window, I see this:

```
Checkers that are compatible with this mode, but will not run until properly configured:

  swagger-cli (automatically disabled) reset
    - may enable: no
    - may run:    nil
    - executable: Not found

Flycheck Mode is enabled.  Use C-u C-c ! x to enable disabled
checkers.
```

If flycheck is trying to find the executable, that won't work, of course, unless somehow I can present "docker" as the executable.

The flycheck docs tell me I can change the executable, but it seems like I would need to change the executable *and* the arguments to the executable, and they don't say how to do that.

**Comment by magoyette** [comment]
I'm archiving this repository since I'm no longer using flycheck-swagger-cli or another OpenAPI linter with Emacs.
