### ISSUE TITLE
Support OpenAPI 3

### ISSUE THREAD

**Issue by arichiardi** [magoyette/flycheck-swagger-cli#2]
Hi there, I was trying to use this checker against my `openapi: 3.0.3` file but it was not correctly running - I tried `flycheck-compile` to see what was happening.

It seems like the regex the package uses filters out files not containing `swagger 2.0` strings.

However, as far as I know, `swagger-cli` [supports OpenAPI 3.0](https://github.com/APIDevTools/swagger-cli#validate-an-api), would you be open to a PR tweak that regex?

**Comment by magoyette** [comment]
I'm archiving this repository since I'm no longer using flycheck-swagger-cli or another Swagger/OpenAPI linter with Emacs.

A fork of flycheck-swagger-cli has [a commit to support OpenAPI 3.0](https://github.com/vercapi/flycheck-swagger-cli/commit/c88435676cc9da1c9a6fb2ac08ab50623d826933).
